// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: twitter/v1alpha/twitter.proto

package twitterconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha "github.com/mayocream/twitter/pkg/connectrpc/twitter/v1alpha"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AccountServiceName is the fully-qualified name of the AccountService service.
	AccountServiceName = "twitter.v1alpha.AccountService"
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "twitter.v1alpha.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AccountServiceCreateAccountProcedure is the fully-qualified name of the AccountService's
	// CreateAccount RPC.
	AccountServiceCreateAccountProcedure = "/twitter.v1alpha.AccountService/CreateAccount"
	// AccountServiceGetAccountProcedure is the fully-qualified name of the AccountService's GetAccount
	// RPC.
	AccountServiceGetAccountProcedure = "/twitter.v1alpha.AccountService/GetAccount"
	// AccountServiceUpdateAccountProcedure is the fully-qualified name of the AccountService's
	// UpdateAccount RPC.
	AccountServiceUpdateAccountProcedure = "/twitter.v1alpha.AccountService/UpdateAccount"
	// AuthServiceLoginProcedure is the fully-qualified name of the AuthService's Login RPC.
	AuthServiceLoginProcedure = "/twitter.v1alpha.AuthService/Login"
	// AuthServiceLogoutProcedure is the fully-qualified name of the AuthService's Logout RPC.
	AuthServiceLogoutProcedure = "/twitter.v1alpha.AuthService/Logout"
)

// AccountServiceClient is a client for the twitter.v1alpha.AccountService service.
type AccountServiceClient interface {
	CreateAccount(context.Context, *connect.Request[v1alpha.CreateAccountRequest]) (*connect.Response[v1alpha.Account], error)
	GetAccount(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha.Account], error)
	UpdateAccount(context.Context, *connect.Request[v1alpha.UpdateAccountRequest]) (*connect.Response[v1alpha.Account], error)
}

// NewAccountServiceClient constructs a client for the twitter.v1alpha.AccountService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAccountServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AccountServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	accountServiceMethods := v1alpha.File_twitter_v1alpha_twitter_proto.Services().ByName("AccountService").Methods()
	return &accountServiceClient{
		createAccount: connect.NewClient[v1alpha.CreateAccountRequest, v1alpha.Account](
			httpClient,
			baseURL+AccountServiceCreateAccountProcedure,
			connect.WithSchema(accountServiceMethods.ByName("CreateAccount")),
			connect.WithClientOptions(opts...),
		),
		getAccount: connect.NewClient[emptypb.Empty, v1alpha.Account](
			httpClient,
			baseURL+AccountServiceGetAccountProcedure,
			connect.WithSchema(accountServiceMethods.ByName("GetAccount")),
			connect.WithClientOptions(opts...),
		),
		updateAccount: connect.NewClient[v1alpha.UpdateAccountRequest, v1alpha.Account](
			httpClient,
			baseURL+AccountServiceUpdateAccountProcedure,
			connect.WithSchema(accountServiceMethods.ByName("UpdateAccount")),
			connect.WithClientOptions(opts...),
		),
	}
}

// accountServiceClient implements AccountServiceClient.
type accountServiceClient struct {
	createAccount *connect.Client[v1alpha.CreateAccountRequest, v1alpha.Account]
	getAccount    *connect.Client[emptypb.Empty, v1alpha.Account]
	updateAccount *connect.Client[v1alpha.UpdateAccountRequest, v1alpha.Account]
}

// CreateAccount calls twitter.v1alpha.AccountService.CreateAccount.
func (c *accountServiceClient) CreateAccount(ctx context.Context, req *connect.Request[v1alpha.CreateAccountRequest]) (*connect.Response[v1alpha.Account], error) {
	return c.createAccount.CallUnary(ctx, req)
}

// GetAccount calls twitter.v1alpha.AccountService.GetAccount.
func (c *accountServiceClient) GetAccount(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha.Account], error) {
	return c.getAccount.CallUnary(ctx, req)
}

// UpdateAccount calls twitter.v1alpha.AccountService.UpdateAccount.
func (c *accountServiceClient) UpdateAccount(ctx context.Context, req *connect.Request[v1alpha.UpdateAccountRequest]) (*connect.Response[v1alpha.Account], error) {
	return c.updateAccount.CallUnary(ctx, req)
}

// AccountServiceHandler is an implementation of the twitter.v1alpha.AccountService service.
type AccountServiceHandler interface {
	CreateAccount(context.Context, *connect.Request[v1alpha.CreateAccountRequest]) (*connect.Response[v1alpha.Account], error)
	GetAccount(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha.Account], error)
	UpdateAccount(context.Context, *connect.Request[v1alpha.UpdateAccountRequest]) (*connect.Response[v1alpha.Account], error)
}

// NewAccountServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAccountServiceHandler(svc AccountServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	accountServiceMethods := v1alpha.File_twitter_v1alpha_twitter_proto.Services().ByName("AccountService").Methods()
	accountServiceCreateAccountHandler := connect.NewUnaryHandler(
		AccountServiceCreateAccountProcedure,
		svc.CreateAccount,
		connect.WithSchema(accountServiceMethods.ByName("CreateAccount")),
		connect.WithHandlerOptions(opts...),
	)
	accountServiceGetAccountHandler := connect.NewUnaryHandler(
		AccountServiceGetAccountProcedure,
		svc.GetAccount,
		connect.WithSchema(accountServiceMethods.ByName("GetAccount")),
		connect.WithHandlerOptions(opts...),
	)
	accountServiceUpdateAccountHandler := connect.NewUnaryHandler(
		AccountServiceUpdateAccountProcedure,
		svc.UpdateAccount,
		connect.WithSchema(accountServiceMethods.ByName("UpdateAccount")),
		connect.WithHandlerOptions(opts...),
	)
	return "/twitter.v1alpha.AccountService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AccountServiceCreateAccountProcedure:
			accountServiceCreateAccountHandler.ServeHTTP(w, r)
		case AccountServiceGetAccountProcedure:
			accountServiceGetAccountHandler.ServeHTTP(w, r)
		case AccountServiceUpdateAccountProcedure:
			accountServiceUpdateAccountHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAccountServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAccountServiceHandler struct{}

func (UnimplementedAccountServiceHandler) CreateAccount(context.Context, *connect.Request[v1alpha.CreateAccountRequest]) (*connect.Response[v1alpha.Account], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("twitter.v1alpha.AccountService.CreateAccount is not implemented"))
}

func (UnimplementedAccountServiceHandler) GetAccount(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha.Account], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("twitter.v1alpha.AccountService.GetAccount is not implemented"))
}

func (UnimplementedAccountServiceHandler) UpdateAccount(context.Context, *connect.Request[v1alpha.UpdateAccountRequest]) (*connect.Response[v1alpha.Account], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("twitter.v1alpha.AccountService.UpdateAccount is not implemented"))
}

// AuthServiceClient is a client for the twitter.v1alpha.AuthService service.
type AuthServiceClient interface {
	Login(context.Context, *connect.Request[v1alpha.LoginRequest]) (*connect.Response[v1alpha.LoginResponse], error)
	Logout(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error)
}

// NewAuthServiceClient constructs a client for the twitter.v1alpha.AuthService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1alpha.File_twitter_v1alpha_twitter_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		login: connect.NewClient[v1alpha.LoginRequest, v1alpha.LoginResponse](
			httpClient,
			baseURL+AuthServiceLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		logout: connect.NewClient[emptypb.Empty, emptypb.Empty](
			httpClient,
			baseURL+AuthServiceLogoutProcedure,
			connect.WithSchema(authServiceMethods.ByName("Logout")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	login  *connect.Client[v1alpha.LoginRequest, v1alpha.LoginResponse]
	logout *connect.Client[emptypb.Empty, emptypb.Empty]
}

// Login calls twitter.v1alpha.AuthService.Login.
func (c *authServiceClient) Login(ctx context.Context, req *connect.Request[v1alpha.LoginRequest]) (*connect.Response[v1alpha.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// Logout calls twitter.v1alpha.AuthService.Logout.
func (c *authServiceClient) Logout(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error) {
	return c.logout.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the twitter.v1alpha.AuthService service.
type AuthServiceHandler interface {
	Login(context.Context, *connect.Request[v1alpha.LoginRequest]) (*connect.Response[v1alpha.LoginResponse], error)
	Logout(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1alpha.File_twitter_v1alpha_twitter_proto.Services().ByName("AuthService").Methods()
	authServiceLoginHandler := connect.NewUnaryHandler(
		AuthServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(authServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLogoutHandler := connect.NewUnaryHandler(
		AuthServiceLogoutProcedure,
		svc.Logout,
		connect.WithSchema(authServiceMethods.ByName("Logout")),
		connect.WithHandlerOptions(opts...),
	)
	return "/twitter.v1alpha.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceLoginProcedure:
			authServiceLoginHandler.ServeHTTP(w, r)
		case AuthServiceLogoutProcedure:
			authServiceLogoutHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) Login(context.Context, *connect.Request[v1alpha.LoginRequest]) (*connect.Response[v1alpha.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("twitter.v1alpha.AuthService.Login is not implemented"))
}

func (UnimplementedAuthServiceHandler) Logout(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("twitter.v1alpha.AuthService.Logout is not implemented"))
}
