[package]
name = "bocchi"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tonic = "*"
prost = "0.13"

[build-dependencies]
tonic-build = "*"
