[package]
name = "bocchi"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "entity", "migration"]

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
tokio = { version = "1", features = ["full"] }
tonic = "*"
prost = "0.13"
sea-orm = { version = "1", features = [
    "sqlx-postgres",
    "runtime-tokio-native-tls",
    "macros",
    "with-chrono",
] }
chrono = "0.4.40"
dotenvy = "0.15.7"
entity = { path = "entity" }
migration = { path = "migration" }
reqwest = { version = "0.12", features = ["json"] }
tracing = "0.1"
tracing-subscriber = "0.3"
jsonwebtoken = "9"
serde = { version = "1.0", features = ["derive"] }
argon2 = "0.5.3"
validator = { version = "0.19", features = ["derive"] }
regex = "1.11.1"
blake3 = "1.6.1"
hex = "0.4.3"
tonic-web = "0.12.3"
tower-http = { version = "*", features = ["full"] }
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-s3 = { version = "1", features = ["behavior-version-latest"] }
infer = "0.19.0"
anyhow = "1.0.97"

[build-dependencies]
tonic-build = "*"

[dev-dependencies]
sea-orm = { version = "1", features = [
    "sqlx-sqlite",
    "runtime-tokio-native-tls",
    "macros",
    "with-chrono",
] }
