[package]
name = "bocchi"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "entity", "migration"]

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
tokio = { version = "1", features = ["full"] }
tonic = "*"
prost = "0.13"
sea-orm = { version = "1", features = [
    "sqlx-postgres",
    "runtime-tokio-native-tls",
    "macros",
    "with-chrono",
] }
chrono = "0.4.40"
dotenvy = "0.15.7"
entity = { path = "entity" }
migration = { path = "migration" }

[build-dependencies]
tonic-build = "*"
