#:schema node_modules/wrangler/config-schema.json
name = "twitter"
main = ".worker-next/index.mjs"

compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

# Minification helps to keep the Worker bundle size down and improve start up time.
minify = true

# Use the new Workers + Assets to host the static frontend files
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

routes = [
    { pattern = "twitter.co.jp", custom_domain = true }
]

[vars]

[observability]
enabled = true
