//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::comment::Entity as Comment;
pub use super::follow::Entity as Follow;
pub use super::like::Entity as Like;
pub use super::post::Entity as Post;
pub use super::repost::Entity as Repost;
pub use super::user::Entity as User;
