// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mayocream/twitter/ent/directmessage"
	"github.com/mayocream/twitter/ent/predicate"
	"github.com/mayocream/twitter/ent/user"
)

// DirectMessageQuery is the builder for querying DirectMessage entities.
type DirectMessageQuery struct {
	config
	ctx          *QueryContext
	order        []directmessage.OrderOption
	inters       []Interceptor
	predicates   []predicate.DirectMessage
	withSender   *UserQuery
	withReceiver *UserQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DirectMessageQuery builder.
func (dmq *DirectMessageQuery) Where(ps ...predicate.DirectMessage) *DirectMessageQuery {
	dmq.predicates = append(dmq.predicates, ps...)
	return dmq
}

// Limit the number of records to be returned by this query.
func (dmq *DirectMessageQuery) Limit(limit int) *DirectMessageQuery {
	dmq.ctx.Limit = &limit
	return dmq
}

// Offset to start from.
func (dmq *DirectMessageQuery) Offset(offset int) *DirectMessageQuery {
	dmq.ctx.Offset = &offset
	return dmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dmq *DirectMessageQuery) Unique(unique bool) *DirectMessageQuery {
	dmq.ctx.Unique = &unique
	return dmq
}

// Order specifies how the records should be ordered.
func (dmq *DirectMessageQuery) Order(o ...directmessage.OrderOption) *DirectMessageQuery {
	dmq.order = append(dmq.order, o...)
	return dmq
}

// QuerySender chains the current query on the "sender" edge.
func (dmq *DirectMessageQuery) QuerySender() *UserQuery {
	query := (&UserClient{config: dmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(directmessage.Table, directmessage.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, directmessage.SenderTable, directmessage.SenderColumn),
		)
		fromU = sqlgraph.SetNeighbors(dmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryReceiver chains the current query on the "receiver" edge.
func (dmq *DirectMessageQuery) QueryReceiver() *UserQuery {
	query := (&UserClient{config: dmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(directmessage.Table, directmessage.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, directmessage.ReceiverTable, directmessage.ReceiverColumn),
		)
		fromU = sqlgraph.SetNeighbors(dmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DirectMessage entity from the query.
// Returns a *NotFoundError when no DirectMessage was found.
func (dmq *DirectMessageQuery) First(ctx context.Context) (*DirectMessage, error) {
	nodes, err := dmq.Limit(1).All(setContextOp(ctx, dmq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{directmessage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dmq *DirectMessageQuery) FirstX(ctx context.Context) *DirectMessage {
	node, err := dmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DirectMessage ID from the query.
// Returns a *NotFoundError when no DirectMessage ID was found.
func (dmq *DirectMessageQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dmq.Limit(1).IDs(setContextOp(ctx, dmq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{directmessage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dmq *DirectMessageQuery) FirstIDX(ctx context.Context) int {
	id, err := dmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DirectMessage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DirectMessage entity is found.
// Returns a *NotFoundError when no DirectMessage entities are found.
func (dmq *DirectMessageQuery) Only(ctx context.Context) (*DirectMessage, error) {
	nodes, err := dmq.Limit(2).All(setContextOp(ctx, dmq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{directmessage.Label}
	default:
		return nil, &NotSingularError{directmessage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dmq *DirectMessageQuery) OnlyX(ctx context.Context) *DirectMessage {
	node, err := dmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DirectMessage ID in the query.
// Returns a *NotSingularError when more than one DirectMessage ID is found.
// Returns a *NotFoundError when no entities are found.
func (dmq *DirectMessageQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dmq.Limit(2).IDs(setContextOp(ctx, dmq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{directmessage.Label}
	default:
		err = &NotSingularError{directmessage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dmq *DirectMessageQuery) OnlyIDX(ctx context.Context) int {
	id, err := dmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DirectMessages.
func (dmq *DirectMessageQuery) All(ctx context.Context) ([]*DirectMessage, error) {
	ctx = setContextOp(ctx, dmq.ctx, ent.OpQueryAll)
	if err := dmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DirectMessage, *DirectMessageQuery]()
	return withInterceptors[[]*DirectMessage](ctx, dmq, qr, dmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (dmq *DirectMessageQuery) AllX(ctx context.Context) []*DirectMessage {
	nodes, err := dmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DirectMessage IDs.
func (dmq *DirectMessageQuery) IDs(ctx context.Context) (ids []int, err error) {
	if dmq.ctx.Unique == nil && dmq.path != nil {
		dmq.Unique(true)
	}
	ctx = setContextOp(ctx, dmq.ctx, ent.OpQueryIDs)
	if err = dmq.Select(directmessage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dmq *DirectMessageQuery) IDsX(ctx context.Context) []int {
	ids, err := dmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dmq *DirectMessageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, dmq.ctx, ent.OpQueryCount)
	if err := dmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, dmq, querierCount[*DirectMessageQuery](), dmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (dmq *DirectMessageQuery) CountX(ctx context.Context) int {
	count, err := dmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dmq *DirectMessageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, dmq.ctx, ent.OpQueryExist)
	switch _, err := dmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (dmq *DirectMessageQuery) ExistX(ctx context.Context) bool {
	exist, err := dmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DirectMessageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dmq *DirectMessageQuery) Clone() *DirectMessageQuery {
	if dmq == nil {
		return nil
	}
	return &DirectMessageQuery{
		config:       dmq.config,
		ctx:          dmq.ctx.Clone(),
		order:        append([]directmessage.OrderOption{}, dmq.order...),
		inters:       append([]Interceptor{}, dmq.inters...),
		predicates:   append([]predicate.DirectMessage{}, dmq.predicates...),
		withSender:   dmq.withSender.Clone(),
		withReceiver: dmq.withReceiver.Clone(),
		// clone intermediate query.
		sql:  dmq.sql.Clone(),
		path: dmq.path,
	}
}

// WithSender tells the query-builder to eager-load the nodes that are connected to
// the "sender" edge. The optional arguments are used to configure the query builder of the edge.
func (dmq *DirectMessageQuery) WithSender(opts ...func(*UserQuery)) *DirectMessageQuery {
	query := (&UserClient{config: dmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dmq.withSender = query
	return dmq
}

// WithReceiver tells the query-builder to eager-load the nodes that are connected to
// the "receiver" edge. The optional arguments are used to configure the query builder of the edge.
func (dmq *DirectMessageQuery) WithReceiver(opts ...func(*UserQuery)) *DirectMessageQuery {
	query := (&UserClient{config: dmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dmq.withReceiver = query
	return dmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Content string `json:"content,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DirectMessage.Query().
//		GroupBy(directmessage.FieldContent).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dmq *DirectMessageQuery) GroupBy(field string, fields ...string) *DirectMessageGroupBy {
	dmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DirectMessageGroupBy{build: dmq}
	grbuild.flds = &dmq.ctx.Fields
	grbuild.label = directmessage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Content string `json:"content,omitempty"`
//	}
//
//	client.DirectMessage.Query().
//		Select(directmessage.FieldContent).
//		Scan(ctx, &v)
func (dmq *DirectMessageQuery) Select(fields ...string) *DirectMessageSelect {
	dmq.ctx.Fields = append(dmq.ctx.Fields, fields...)
	sbuild := &DirectMessageSelect{DirectMessageQuery: dmq}
	sbuild.label = directmessage.Label
	sbuild.flds, sbuild.scan = &dmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DirectMessageSelect configured with the given aggregations.
func (dmq *DirectMessageQuery) Aggregate(fns ...AggregateFunc) *DirectMessageSelect {
	return dmq.Select().Aggregate(fns...)
}

func (dmq *DirectMessageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range dmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, dmq); err != nil {
				return err
			}
		}
	}
	for _, f := range dmq.ctx.Fields {
		if !directmessage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dmq.path != nil {
		prev, err := dmq.path(ctx)
		if err != nil {
			return err
		}
		dmq.sql = prev
	}
	return nil
}

func (dmq *DirectMessageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DirectMessage, error) {
	var (
		nodes       = []*DirectMessage{}
		withFKs     = dmq.withFKs
		_spec       = dmq.querySpec()
		loadedTypes = [2]bool{
			dmq.withSender != nil,
			dmq.withReceiver != nil,
		}
	)
	if dmq.withSender != nil || dmq.withReceiver != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, directmessage.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DirectMessage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DirectMessage{config: dmq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := dmq.withSender; query != nil {
		if err := dmq.loadSender(ctx, query, nodes, nil,
			func(n *DirectMessage, e *User) { n.Edges.Sender = e }); err != nil {
			return nil, err
		}
	}
	if query := dmq.withReceiver; query != nil {
		if err := dmq.loadReceiver(ctx, query, nodes, nil,
			func(n *DirectMessage, e *User) { n.Edges.Receiver = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (dmq *DirectMessageQuery) loadSender(ctx context.Context, query *UserQuery, nodes []*DirectMessage, init func(*DirectMessage), assign func(*DirectMessage, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*DirectMessage)
	for i := range nodes {
		if nodes[i].user_sent_messages == nil {
			continue
		}
		fk := *nodes[i].user_sent_messages
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_sent_messages" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (dmq *DirectMessageQuery) loadReceiver(ctx context.Context, query *UserQuery, nodes []*DirectMessage, init func(*DirectMessage), assign func(*DirectMessage, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*DirectMessage)
	for i := range nodes {
		if nodes[i].user_received_messages == nil {
			continue
		}
		fk := *nodes[i].user_received_messages
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_received_messages" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (dmq *DirectMessageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dmq.querySpec()
	_spec.Node.Columns = dmq.ctx.Fields
	if len(dmq.ctx.Fields) > 0 {
		_spec.Unique = dmq.ctx.Unique != nil && *dmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, dmq.driver, _spec)
}

func (dmq *DirectMessageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(directmessage.Table, directmessage.Columns, sqlgraph.NewFieldSpec(directmessage.FieldID, field.TypeInt))
	_spec.From = dmq.sql
	if unique := dmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if dmq.path != nil {
		_spec.Unique = true
	}
	if fields := dmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, directmessage.FieldID)
		for i := range fields {
			if fields[i] != directmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := dmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dmq *DirectMessageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dmq.driver.Dialect())
	t1 := builder.Table(directmessage.Table)
	columns := dmq.ctx.Fields
	if len(columns) == 0 {
		columns = directmessage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dmq.sql != nil {
		selector = dmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dmq.ctx.Unique != nil && *dmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range dmq.predicates {
		p(selector)
	}
	for _, p := range dmq.order {
		p(selector)
	}
	if offset := dmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DirectMessageGroupBy is the group-by builder for DirectMessage entities.
type DirectMessageGroupBy struct {
	selector
	build *DirectMessageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dmgb *DirectMessageGroupBy) Aggregate(fns ...AggregateFunc) *DirectMessageGroupBy {
	dmgb.fns = append(dmgb.fns, fns...)
	return dmgb
}

// Scan applies the selector query and scans the result into the given value.
func (dmgb *DirectMessageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dmgb.build.ctx, ent.OpQueryGroupBy)
	if err := dmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DirectMessageQuery, *DirectMessageGroupBy](ctx, dmgb.build, dmgb, dmgb.build.inters, v)
}

func (dmgb *DirectMessageGroupBy) sqlScan(ctx context.Context, root *DirectMessageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dmgb.fns))
	for _, fn := range dmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dmgb.flds)+len(dmgb.fns))
		for _, f := range *dmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DirectMessageSelect is the builder for selecting fields of DirectMessage entities.
type DirectMessageSelect struct {
	*DirectMessageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dms *DirectMessageSelect) Aggregate(fns ...AggregateFunc) *DirectMessageSelect {
	dms.fns = append(dms.fns, fns...)
	return dms
}

// Scan applies the selector query and scans the result into the given value.
func (dms *DirectMessageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dms.ctx, ent.OpQuerySelect)
	if err := dms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DirectMessageQuery, *DirectMessageSelect](ctx, dms.DirectMessageQuery, dms, dms.inters, v)
}

func (dms *DirectMessageSelect) sqlScan(ctx context.Context, root *DirectMessageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dms.fns))
	for _, fn := range dms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
