// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mayocream/twitter/ent/hashtag"
	"github.com/mayocream/twitter/ent/predicate"
	"github.com/mayocream/twitter/ent/tweet"
)

// HashtagUpdate is the builder for updating Hashtag entities.
type HashtagUpdate struct {
	config
	hooks    []Hook
	mutation *HashtagMutation
}

// Where appends a list predicates to the HashtagUpdate builder.
func (hu *HashtagUpdate) Where(ps ...predicate.Hashtag) *HashtagUpdate {
	hu.mutation.Where(ps...)
	return hu
}

// SetName sets the "name" field.
func (hu *HashtagUpdate) SetName(s string) *HashtagUpdate {
	hu.mutation.SetName(s)
	return hu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (hu *HashtagUpdate) SetNillableName(s *string) *HashtagUpdate {
	if s != nil {
		hu.SetName(*s)
	}
	return hu
}

// AddTweetIDs adds the "tweets" edge to the Tweet entity by IDs.
func (hu *HashtagUpdate) AddTweetIDs(ids ...int) *HashtagUpdate {
	hu.mutation.AddTweetIDs(ids...)
	return hu
}

// AddTweets adds the "tweets" edges to the Tweet entity.
func (hu *HashtagUpdate) AddTweets(t ...*Tweet) *HashtagUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return hu.AddTweetIDs(ids...)
}

// Mutation returns the HashtagMutation object of the builder.
func (hu *HashtagUpdate) Mutation() *HashtagMutation {
	return hu.mutation
}

// ClearTweets clears all "tweets" edges to the Tweet entity.
func (hu *HashtagUpdate) ClearTweets() *HashtagUpdate {
	hu.mutation.ClearTweets()
	return hu
}

// RemoveTweetIDs removes the "tweets" edge to Tweet entities by IDs.
func (hu *HashtagUpdate) RemoveTweetIDs(ids ...int) *HashtagUpdate {
	hu.mutation.RemoveTweetIDs(ids...)
	return hu
}

// RemoveTweets removes "tweets" edges to Tweet entities.
func (hu *HashtagUpdate) RemoveTweets(t ...*Tweet) *HashtagUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return hu.RemoveTweetIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (hu *HashtagUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, hu.sqlSave, hu.mutation, hu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (hu *HashtagUpdate) SaveX(ctx context.Context) int {
	affected, err := hu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (hu *HashtagUpdate) Exec(ctx context.Context) error {
	_, err := hu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hu *HashtagUpdate) ExecX(ctx context.Context) {
	if err := hu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (hu *HashtagUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(hashtag.Table, hashtag.Columns, sqlgraph.NewFieldSpec(hashtag.FieldID, field.TypeInt))
	if ps := hu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := hu.mutation.Name(); ok {
		_spec.SetField(hashtag.FieldName, field.TypeString, value)
	}
	if hu.mutation.TweetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   hashtag.TweetsTable,
			Columns: hashtag.TweetsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := hu.mutation.RemovedTweetsIDs(); len(nodes) > 0 && !hu.mutation.TweetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   hashtag.TweetsTable,
			Columns: hashtag.TweetsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := hu.mutation.TweetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   hashtag.TweetsTable,
			Columns: hashtag.TweetsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, hu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hashtag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	hu.mutation.done = true
	return n, nil
}

// HashtagUpdateOne is the builder for updating a single Hashtag entity.
type HashtagUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HashtagMutation
}

// SetName sets the "name" field.
func (huo *HashtagUpdateOne) SetName(s string) *HashtagUpdateOne {
	huo.mutation.SetName(s)
	return huo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (huo *HashtagUpdateOne) SetNillableName(s *string) *HashtagUpdateOne {
	if s != nil {
		huo.SetName(*s)
	}
	return huo
}

// AddTweetIDs adds the "tweets" edge to the Tweet entity by IDs.
func (huo *HashtagUpdateOne) AddTweetIDs(ids ...int) *HashtagUpdateOne {
	huo.mutation.AddTweetIDs(ids...)
	return huo
}

// AddTweets adds the "tweets" edges to the Tweet entity.
func (huo *HashtagUpdateOne) AddTweets(t ...*Tweet) *HashtagUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return huo.AddTweetIDs(ids...)
}

// Mutation returns the HashtagMutation object of the builder.
func (huo *HashtagUpdateOne) Mutation() *HashtagMutation {
	return huo.mutation
}

// ClearTweets clears all "tweets" edges to the Tweet entity.
func (huo *HashtagUpdateOne) ClearTweets() *HashtagUpdateOne {
	huo.mutation.ClearTweets()
	return huo
}

// RemoveTweetIDs removes the "tweets" edge to Tweet entities by IDs.
func (huo *HashtagUpdateOne) RemoveTweetIDs(ids ...int) *HashtagUpdateOne {
	huo.mutation.RemoveTweetIDs(ids...)
	return huo
}

// RemoveTweets removes "tweets" edges to Tweet entities.
func (huo *HashtagUpdateOne) RemoveTweets(t ...*Tweet) *HashtagUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return huo.RemoveTweetIDs(ids...)
}

// Where appends a list predicates to the HashtagUpdate builder.
func (huo *HashtagUpdateOne) Where(ps ...predicate.Hashtag) *HashtagUpdateOne {
	huo.mutation.Where(ps...)
	return huo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (huo *HashtagUpdateOne) Select(field string, fields ...string) *HashtagUpdateOne {
	huo.fields = append([]string{field}, fields...)
	return huo
}

// Save executes the query and returns the updated Hashtag entity.
func (huo *HashtagUpdateOne) Save(ctx context.Context) (*Hashtag, error) {
	return withHooks(ctx, huo.sqlSave, huo.mutation, huo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (huo *HashtagUpdateOne) SaveX(ctx context.Context) *Hashtag {
	node, err := huo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (huo *HashtagUpdateOne) Exec(ctx context.Context) error {
	_, err := huo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (huo *HashtagUpdateOne) ExecX(ctx context.Context) {
	if err := huo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (huo *HashtagUpdateOne) sqlSave(ctx context.Context) (_node *Hashtag, err error) {
	_spec := sqlgraph.NewUpdateSpec(hashtag.Table, hashtag.Columns, sqlgraph.NewFieldSpec(hashtag.FieldID, field.TypeInt))
	id, ok := huo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Hashtag.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := huo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hashtag.FieldID)
		for _, f := range fields {
			if !hashtag.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hashtag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := huo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := huo.mutation.Name(); ok {
		_spec.SetField(hashtag.FieldName, field.TypeString, value)
	}
	if huo.mutation.TweetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   hashtag.TweetsTable,
			Columns: hashtag.TweetsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := huo.mutation.RemovedTweetsIDs(); len(nodes) > 0 && !huo.mutation.TweetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   hashtag.TweetsTable,
			Columns: hashtag.TweetsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := huo.mutation.TweetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   hashtag.TweetsTable,
			Columns: hashtag.TweetsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Hashtag{config: huo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, huo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hashtag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	huo.mutation.done = true
	return _node, nil
}
