name: App Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: bun install

      - name: Build iOS app
        working-directory: packages/expo
        run: eas build --platform ios --local --non-interactive --output ${{ github.workspace }}/release.ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: ${{ github.workspace }}/release.ipa

  submit:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - uses: actions/download-artifact@v4
        with:
          name: release
          path: app

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: bun install

      - name: Submit
        working-directory: packages/expo
        run: eas submit --platform android --path ${{ github.workspace }}}/app/release.apk --non-interactive
