name: App Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: pnpm install

      - name: EAS Update
        working-directory: packages/expo
        run: eas update --branch main --non-interactive --auto

      - name: Build iOS app
        working-directory: packages/expo
        run: eas build --platform ios --local --non-interactive --output ${{ github.workspace }}/app-release.ipa

      - name: Submit
        run: eas submit --platform ios --path ${{ github.workspace }}/app-release.ipa --non-interactive

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ github.workspace }}/app-release.ipa
