name: Cloud Run

on:
  push:
    branches: ['main']

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: hello-cloud-run
          image: gcr.io/cloudrun/hello

      - name: Use output
        run: curl "${{ steps.deploy.outputs.url }}"
