name: 'Build and Push Docker Image'

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'mayocream'
          password: '${{ secrets.DOCKER_PAT }}'

      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="mayocream/twitter:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"
