name: 'Testing'

on:
  push:
    branches:
      - 'main'

jobs:
  testing:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Run Tests'
        run: make test
