name: Web Deployment

on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Build Project
        run: bunx expo export -p web

      - name: Deploy Project Artifacts to Vercel
        run: bun vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
