name: Web Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Pull environment variables
        working-directory: packages/expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: bun eas env:pull --environment production

      - name: Build Project
        working-directory: packages/expo
        run: bunx expo export -p web

      - name: Deploy Project Artifacts to Vercel
        working-directory: packages/expo
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: bun vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} dist
